[tools]
opentofu = "1.11"
terragrunt = "0.96"

[env]
SOPS_AGE_KEY_FILE = "{{ exec(command='git rev-parse --show-toplevel')}}/sops/key.txt"

[tasks.hello]
description = "Hello, mise!"
run = "echo \"Hello, mise!\""

